global:
  scrape_interval: 15s # How often to scrape metrics

scrape_configs:
  # OpenTelemetry Collector - Receives OTLP from Portkey and converts to Prometheus metrics
  - job_name: 'portkey_otlp_metrics'
    static_configs:
      - targets: ['host.containers.internal:8889']
    metrics_path: '/metrics'
    scrape_timeout: 10s
    
  # Portkey Gateway health monitoring
  - job_name: 'portkey_gateway_health'
    static_configs:
      - targets: ['host.containers.internal:8787']
    metrics_path: '/'
    scrape_timeout: 10s
    
  # Ollama Monitoring Proxy - includes Portkey routing metrics
  - job_name: 'ollama_monitoring_proxy'
    static_configs:
      - targets: ['localhost:8001']
    metrics_path: '/metrics'
    scrape_timeout: 10s
    metric_relabel_configs:
      # Keep all ollama_proxy_ metrics including routing labels
      - source_labels: [__name__]
        regex: 'ollama_proxy_.*'
        action: keep
    
  # Ollama direct monitoring (if it has metrics endpoint)
  - job_name: 'ollama'
    static_configs:
      - targets: ['localhost:11434']
    metrics_path: '/metrics'
    scrape_timeout: 10s
    
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
