global:
  scrape_interval: 15s # How often to scrape metrics

scrape_configs:
  - job_name: 'llamastack_app'
    # This job defines how to find and scrape metrics from your Python app.
    static_configs:
      - targets: ['host.containers.internal:8000']
        # 'host.containers.internal' is a special DNS name for Podman that allows the
        # container to connect to a service running on the host machine (your Mac).
        # It is the equivalent of 'host.docker.internal' for Docker.
