global:
  scrape_interval: 15s # How often to scrape metrics

scrape_configs:
  # Ollama Monitoring Proxy - LLM request metrics
  - job_name: 'ollama-monitoring-proxy'
    static_configs:
      - targets: ['host.containers.internal:8001']
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 10s

  # Note: System metrics (CPU, memory, GPU, power) are collected by the ollama-monitoring-proxy
  # No separate system metrics collector needed as the proxy handles it all

  # Note: Ollama doesn't expose Prometheus metrics by default
  # - job_name: 'ollama'
  #   static_configs:
  #     - targets: ['host.containers.internal:11434']
  #   metrics_path: '/metrics'
  #   scrape_timeout: 10s

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
